import AuthController from './AuthController'
import ForgotPasswordController from './ForgotPasswordController'
import DashboardController from './DashboardController'
import ActionApplicantProgrammingLanguageController from './ActionApplicantProgrammingLanguageController'
import ActionApplicantSkillController from './ActionApplicantSkillController'
import IntermediateApplicationController from './IntermediateApplicationController'
import IntermediateInterviewerController from './IntermediateInterviewerController'
import UserController from './UserController'
import ResourceScheduleController from './ResourceScheduleController'
import ActionApplicationController from './ActionApplicationController'
import ApplicationImportController from './ApplicationImportController'
import ActionBatchController from './ActionBatchController'
import ActionApplicantController from './ActionApplicantController'
import IntermediateProjectController from './IntermediateProjectController'
import IntermediateRequisitionController from './IntermediateRequisitionController'
import IntermediateApplicantController from './IntermediateApplicantController'
import IntermediateApplicantSkillController from './IntermediateApplicantSkillController'
import IntermediateApplicantWorkExperienceController from './IntermediateApplicantWorkExperienceController'
import Settings from './Settings'
const Controllers = {
    AuthController: Object.assign(AuthController, AuthController),
ForgotPasswordController: Object.assign(ForgotPasswordController, ForgotPasswordController),
DashboardController: Object.assign(DashboardController, DashboardController),
ActionApplicantProgrammingLanguageController: Object.assign(ActionApplicantProgrammingLanguageController, ActionApplicantProgrammingLanguageController),
ActionApplicantSkillController: Object.assign(ActionApplicantSkillController, ActionApplicantSkillController),
IntermediateApplicationController: Object.assign(IntermediateApplicationController, IntermediateApplicationController),
IntermediateInterviewerController: Object.assign(IntermediateInterviewerController, IntermediateInterviewerController),
UserController: Object.assign(UserController, UserController),
ResourceScheduleController: Object.assign(ResourceScheduleController, ResourceScheduleController),
ActionApplicationController: Object.assign(ActionApplicationController, ActionApplicationController),
ApplicationImportController: Object.assign(ApplicationImportController, ApplicationImportController),
ActionBatchController: Object.assign(ActionBatchController, ActionBatchController),
ActionApplicantController: Object.assign(ActionApplicantController, ActionApplicantController),
IntermediateProjectController: Object.assign(IntermediateProjectController, IntermediateProjectController),
IntermediateRequisitionController: Object.assign(IntermediateRequisitionController, IntermediateRequisitionController),
IntermediateApplicantController: Object.assign(IntermediateApplicantController, IntermediateApplicantController),
IntermediateApplicantSkillController: Object.assign(IntermediateApplicantSkillController, IntermediateApplicantSkillController),
IntermediateApplicantWorkExperienceController: Object.assign(IntermediateApplicantWorkExperienceController, IntermediateApplicantWorkExperienceController),
Settings: Object.assign(Settings, Settings),
}

export default Controllers